name: Remove old artifacts

on:
  push:

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 hour'
        # Optional inputs
        skip-recent: 2
